language: generic
dist: bionic

before_install:
  - mkdir $HOME/.fonts
  - cp -a $TRAVIS_BUILD_DIR/fonts/. $HOME/.fonts/
  - fc-cache -f -v

install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script:
  - cp cv.tex Eshwen_Bhal_CV.tex
  - cp cv_targeted_industries/cv_academic.tex cv_targeted_industries/Eshwen_Bhal_CV_academic.tex
  - cp cv_targeted_industries/cv_data_science.tex cv_targeted_industries/Eshwen_Bhal_CV_data_science.tex
  - cp cv_targeted_industries/cv_research.tex cv_targeted_industries/Eshwen_Bhal_CV_research.tex
  - cp cv_targeted_industries/cv_software.tex cv_targeted_industries/Eshwen_Bhal_CV_software.tex

script:
  # Texliveonfly will download packages automatically
  - texliveonfly -c xelatex Eshwen_Bhal_CV.tex

  # Compile each version of the document
  - xelatex Eshwen_Bhal_CV.tex
  - cd cv_targeted_industries
  - xelatex Eshwen_Bhal_CV_academic.tex
  - xelatex Eshwen_Bhal_CV_data_science.tex
  - xelatex Eshwen_Bhal_CV_research.tex
  - xelatex Eshwen_Bhal_CV_software.tex
  - cd -

deploy:
  provider: releases
  token: $GITHUB_CI_TOKEN  # Secure variable for GitHub token. Set in settings page of repository (on Travis CI)
  file:
    - ./Eshwen_Bhal_CV.pdf
    - ./cv_targeted_industries/Eshwen_Bhal_CV_academic.tex
    - ./cv_targeted_industries/Eshwen_Bhal_CV_data_science.tex
    - ./cv_targeted_industries/Eshwen_Bhal_CV_research.tex
    - ./cv_targeted_industries/Eshwen_Bhal_CV_software.tex
  skip_cleanup: true
  on:
    tags: true
