language: generic
dist: bionic

before_install:
  - mkdir $HOME/.fonts
  - cp -a $TRAVIS_BUILD_DIR/fonts/. $HOME/.fonts/
  - fc-cache -f -v

install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script:
  - cp cv.tex Eshwen_Bhal_CV.tex
script:
  # Texliveonfly will download packages automatically
  - texliveonfly -c xelatex Eshwen_Bhal_CV.tex

  # Compile
  - xelatex Eshwen_Bhal_CV.tex

deploy:
  provider: releases
  token: $GITHUB_CI_TOKEN  # Secure variable for GitHub token. Set in settings page of repository (on Travis CI)
  file:
    - ./Eshwen_Bhal_CV.pdf
  skip_cleanup: true
  on:
    tags: true
